# from ml_pipeline.data_exploratory_analysis.base_eda import BaseExploratoryDataAnalysis
# from .data_exploratory_analysis.base_eda import BaseExploratoryDataAnalysis

import ml_pipeline.data_exploratory_analysis.base_eda

from base_eda import BaseExploratoryDataAnalysis
# import .ml_pipeline.data_exploratory_analysis.base_eda.BaseExploratoryDataAnalysis